# 4주놀이 – 로컬 개발용 Compose
#   • MariaDB 11  (호스트 포트 3308)
#   • Redis 7    (기본 6379)

services:
  mariadb:
    container_name: mariadb          # 원하면 생략 가능
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "0420"
      MARIADB_DATABASE: "fourju"
      MARIADB_USER: "root"
      MARIADB_PASSWORD: "0420"
      TZ: "Asia/Seoul"
    ports:
      - "3308:3306"                  # 호스트 3308 → 컨테이너 3306
    volumes:
      - db_data:/var/lib/mysql       # 로컬 볼륨에 데이터 유지

  redis:
    container_name: redis
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data:
