version: "3.9"
services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: fourju
      MARIADB_USER: fourju
      MARIADB_PASSWORD: devpass
    ports: ["3308:3308"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
